//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingColledge.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Housing_Complex
    {
        public int Id_Housing_Complex { get; set; }
        public Nullable<int> Apartment_Number { get; set; }
        public Nullable<decimal> Square { get; set; }
        public Nullable<int> Rooms { get; set; }
        public Nullable<int> Entrance { get; set; }
        public Nullable<int> Storey { get; set; }
        public string Status_Sale { get; set; }
        public Nullable<decimal> Additional_Cost_Of_Finishing { get; set; }
        public Nullable<decimal> Cost_Apartment_Construction { get; set; }
    }
}
